/*
 * FreeBASIC Language Server
 * Copyright (C) 2026 Ebben Feagan
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// M9 grammar freshness gate + catalog-completeness checks.
//
// Regenerates the editor grammars in memory through the same emitter the
// `gen_grammar` tool uses, then byte-diffs the result against the committed
// `docs/grammar/*` files. Also asserts the structural facts the grammar must
// hold: the emitted JSON parses, every lexer token category has a pattern, and
// every catalog keyword/operator survived into the grammar.

#include "grammar_emitter.h"

#include "language.h"

#include <cstdio>
#include <fstream>
#include <iterator>
#include <set>
#include <string>
#include <string_view>
#include <vector>

#include <rapidjson/document.h>

#ifndef GRAMMAR_DIR
#define GRAMMAR_DIR "docs/grammar"
#endif

static int failures = 0;

#define CHECK(cond)                                                            \
  do {                                                                         \
    if (!(cond)) {                                                             \
      std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);              \
      ++failures;                                                              \
    }                                                                          \
  } while (0)

static std::string readFile(std::string const &path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) {
    return {};
  }
  return std::string(std::istreambuf_iterator<char>(in),
                     std::istreambuf_iterator<char>());
}

// Split a `a|b|c` alternation body into its alternatives.
static std::vector<std::string> splitAlternation(std::string const &body) {
  std::vector<std::string> out;
  std::string cur;
  for (char const c : body) {
    if (c == '|') {
      out.push_back(cur);
      cur.clear();
    } else {
      cur.push_back(c);
    }
  }
  out.push_back(cur);
  return out;
}

int main() {
  std::vector<fbgrammar::GeneratedFile> const files = fbgrammar::generate();
  CHECK(files.size() == 3);

  // Freshness: the committed `docs/grammar/*` must equal the regenerated bytes.
  std::string committedTm;
  for (fbgrammar::GeneratedFile const &f : files) {
    std::string const path = std::string(GRAMMAR_DIR) + "/" + f.relativePath;
    std::string const committed = readFile(path);
    if (committed.empty()) {
      std::printf("FAIL: cannot read committed %s\n", path.c_str());
      ++failures;
      continue;
    }
    if (committed != f.content) {
      std::printf("FAIL: %s is stale; run `cmake --build build --target "
                  "grammar`\n",
                  path.c_str());
      ++failures;
    }
    if (f.relativePath == "freebasic.tmLanguage.json") {
      committedTm = committed;
    }
  }
  CHECK(!committedTm.empty());

  // The committed JSON must parse.
  rapidjson::Document doc;
  doc.Parse(committedTm.c_str());
  CHECK(!doc.HasParseError());
  if (doc.HasParseError() || !doc.IsObject() || !doc.HasMember("patterns") ||
      !doc["patterns"].IsArray()) {
    std::printf("grammar_checks: %d failures\n", failures);
    return failures == 0 ? 0 : 1;
  }

  // Category coverage: one pattern per lexer token category.
  std::set<std::string> names;
  std::set<std::string> keywordWords;
  std::string operatorMatch;
  for (rapidjson::Value const &pattern : doc["patterns"].GetArray()) {
    CHECK(pattern.IsObject());
    if (!pattern.HasMember("name") || !pattern["name"].IsString()) {
      continue;
    }
    std::string const name = pattern["name"].GetString();
    names.insert(name);
    if (name == "keyword.freebasic" && pattern.HasMember("match")) {
      std::string const match = pattern["match"].GetString();
      std::string const prefix = "(?i:\\b(?:";
      std::string const suffix = ")\\b)";
      CHECK(match.rfind(prefix, 0) == 0 &&
            match.size() >= prefix.size() + suffix.size());
      if (match.rfind(prefix, 0) == 0 &&
          match.size() >= prefix.size() + suffix.size()) {
        std::string const body = match.substr(
            prefix.size(), match.size() - prefix.size() - suffix.size());
        for (std::string const &word : splitAlternation(body)) {
          keywordWords.insert(word);
        }
      }
    }
    if (name == "operator.freebasic" && pattern.HasMember("match")) {
      operatorMatch = pattern["match"].GetString();
    }
  }
  CHECK(names.count("comment.line.freebasic") == 1);
  CHECK(names.count("comment.line.rem.freebasic") == 1);
  CHECK(names.count("string.freebasic") == 1);
  CHECK(names.count("number.freebasic") == 1);
  CHECK(names.count("macro.freebasic") == 1);
  CHECK(names.count("keyword.freebasic") == 1);
  CHECK(names.count("operator.freebasic") == 1);
  CHECK(names.count("variable.freebasic") == 1);

  // The block-comment rule lives in the repository and nests by include.
  CHECK(doc.HasMember("repository") && doc["repository"].IsObject());
  if (doc.HasMember("repository") && doc["repository"].IsObject()) {
    rapidjson::Value const &repo = doc["repository"];
    CHECK(repo.HasMember("block_comment"));
    if (repo.HasMember("block_comment")) {
      rapidjson::Value const &bc = repo["block_comment"];
      CHECK(bc.IsObject() && bc.HasMember("name") &&
            std::string(bc["name"].GetString()) == "comment.block.freebasic");
    }
  }

  // Keywords: every reserved word (built-in types included) is present, and
  // nothing extra. Reserved words are plain `[a-z]+`, so alternation entries
  // are unescaped.
  std::set<std::string> expectedWords;
  for (std::string_view const w : fblang::reservedWords()) {
    expectedWords.emplace(w);
  }
  CHECK(keywordWords == expectedWords);
  if (keywordWords != expectedWords) {
    for (std::string const &w : expectedWords) {
      if (keywordWords.count(w) == 0) {
        std::printf("  keyword missing: %s\n", w.c_str());
      }
    }
  }

  // Operators: every catalog entry survives into the pattern. A substring
  // check is safe here (a shorter operator inside a longer one only risks a
  // false pass, never a false failure).
  for (std::string_view const op : fblang::symbolOperators()) {
    std::string escaped;
    for (char const c : op) {
      if (std::string_view(".^$*+?()[]{}|\\/").find(c) !=
          std::string_view::npos) {
        escaped.push_back('\\');
      }
      escaped.push_back(c);
    }
    if (operatorMatch.find(escaped) == std::string::npos) {
      std::printf("  operator missing: %s\n", std::string(op).c_str());
      ++failures;
    }
  }

  if (failures == 0) {
    std::printf("grammar_checks: all passed\n");
    return 0;
  }
  std::printf("grammar_checks: %d failures\n", failures);
  return 1;
}
