" Vim syntax file for FreeBASIC.
" Generated by tools/gen_grammar from src/language.cpp; do not edit by hand.
" Install: ~/.vim/syntax/freebasic.vim, or a Neovim runtime path. See editors/README.md.

if exists("b:current_syntax")
  finish
endif
let b:current_syntax = "freebasic"

syn case ignore

" Comments. Vim regions nest only when the contained region is
" listed in `contains`, so /'...'/ nesting is approximated.
syn region  fbBlockComment start=+/\'+ end=+'/+ contains=fbBlockComment
syn match   fbComment /'.*$/ contains=fbBlockComment
syn match   fbRemComment /\<REM\>.*$/ contains=fbTodo
syn keyword fbTodo TODO FIXME XXX contained

" Strings; a doubled quote is an escaped quote.
syn region  fbString start=/[!$]\?"/ end=/"/ skip=/""/

" Numbers (radix, decimal, leading-dot) with an optional suffix.
syn match   fbNumber /&[HhOoBb][0-9A-Fa-f]\+[%&!#]\?/
syn match   fbNumber /\<\d\+\(\.\d\+\)\?\([eE][+-]\?\d\+\)\?[%&!#]\?/
syn match   fbNumber /\.\d\+\([eE][+-]\?\d\+\)\?[%&!#]\?/

" Preprocessor / metacommand lines.
syn match   fbPreProc /^\s*#.*$/

" Keywords (generated from src/language.cpp).
syn keyword fbKeyword abs abstract access acos alias allocate and andalso any append as asc asin asm assert assertwarn atan2 atn base beep bin binary bit bitreset bitset bload boolean bsave byref byte byval call callocate case cast cbool cbyte cdbl cdecl chain chdir chr cint circle class clear clng clngint close cls color command common condbroadcast condcreate conddestroy condsignal condwait const constructor continue cos cptr cshort csign csng csrlin cubyte cuint culng culngint cunsg curdir cushort cvd cvi cvl cvlongint cvs cvshort data date deallocate declare defbyte defdbl defined defint deflng deflongint defshort defsng defstr defubyte defuint defulongint defushort delete destructor dim dir do double draw dylibfree dylibload dylibsymbol else elseif encoding end endif enum environ eof eqv erase erfn erl ermn err error exec exepath exit exp explicit export extends extern false field fix flip for frac fre freefile function get getjoystick getkey getmouse gosub goto hex hibyte hiword if iif
syn keyword fbKeyword imageconvertrow imagecreate imagedestroy imageinfo imp implements import inkey inp input instr instrrev int integer is kill lbound lcase left len let lib line lobyte loc local locate lock lof log long longint loop loword lpos lprint lset ltrim mid mkd mkdir mki mkl mklongint mks mkshort mod multikey mutexcreate mutexdestroy mutexlock mutexunlock name namespace new next not object oct offsetof open operator or orelse out output overload paint palette pascal pcopy peek pmap point pointcoord pointer poke pos preserve preset print private procptr property pset ptr public put random randomize read reallocate redim rem reset restore resume return rgb rgba right rmdir rnd rset rtrim run sadd scope screen screencontrol screencopy screenevent screenglproc screeninfo screenlist screenlock screenptr screenres screenset screensync screenunlock seek select setdate setenviron setmouse settime sgn shared shell shl short shr sin single sizeof sleep space spc sqr static stdcall step stop str string strptr sub swap system
syn keyword fbKeyword tab tan then threadcall threadcreate threadwait time timer to trim true type typeof ubound ubyte ucase uinteger ulong ulongint union unlock unsigned until ushort using val valint vallng valuint valulng var varptr view virtual wait wbin wchr wend whex while width window windowtitle winput with woct write wspace wstr wstring xor zstring

" Operators, longest first so multi-char operators win. `\V` makes
" the pattern very nomagic, so only `\` and `/` need escaping.
syn match   fbOperator /\V~/
syn match   fbOperator /\V|/
syn match   fbOperator /\V^/
syn match   fbOperator /\V\\/
syn match   fbOperator /\V@/
syn match   fbOperator /\V?/
syn match   fbOperator /\V>/
syn match   fbOperator /\V=/
syn match   fbOperator /\V</
syn match   fbOperator /\V\//
syn match   fbOperator /\V./
syn match   fbOperator /\V-/
syn match   fbOperator /\V+/
syn match   fbOperator /\V*/
syn match   fbOperator /\V&/
syn match   fbOperator /\V\\=/
syn match   fbOperator /\V>=/
syn match   fbOperator /\V<>/
syn match   fbOperator /\V<=/
syn match   fbOperator /\V\/=/
syn match   fbOperator /\V->/
syn match   fbOperator /\V-=/
syn match   fbOperator /\V+=/
syn match   fbOperator /\V*=/
syn match   fbOperator /\V&=/
syn match   fbOperator /\V.../

" Identifiers with an optional type-suffix char.
syn match   fbIdentifier /[A-Za-z_][A-Za-z0-9_]*[%&!#$]\?/

hi def link fbBlockComment Comment
hi def link fbComment      Comment
hi def link fbRemComment   Comment
hi def link fbTodo         Todo
hi def link fbString       String
hi def link fbNumber       Number
hi def link fbPreProc      PreProc
hi def link fbKeyword      Keyword
hi def link fbOperator     Operator
hi def link fbIdentifier   Identifier
