/*
 * FreeBASIC Language Server
 * Copyright (C) 2026 Ebben Feagan
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include "fbc_catalog.h"

#include <charconv>
#include <cstddef>
#include <string>
#include <system_error>
#include <vector>

namespace fbc_catalog {
namespace {

// Split a five-column row on tabs. Returns false when the row is not shaped
// like a catalog line (blank, comment, or a stray field count).
bool splitRow(std::string_view line, std::string_view &kind, int &number,
              std::string_view &name, std::string_view &text, int &level) {
  std::string_view field[5];
  std::size_t start = 0;
  for (int i = 0; i < 5; ++i) {
    std::size_t const end = line.find('\t', start);
    if (i < 4) {
      if (end == std::string_view::npos) {
        return false;
      }
      field[i] = line.substr(start, end - start);
      start = end + 1;
    } else {
      // The fifth field is everything left; a tab inside it means the row is
      // not one the extractor wrote.
      if (end != std::string_view::npos) {
        return false;
      }
      field[i] = line.substr(start);
    }
  }
  if (field[0].size() != 1) {
    return false;
  }
  kind = field[0];
  name = field[2];
  text = field[3];
  auto parse = [](std::string_view s, int &out) {
    if (s.empty()) {
      return false;
    }
    auto const *begin = s.data();
    auto const *end = begin + s.size();
    auto const result = std::from_chars(begin, end, out);
    return result.ec == std::errc() && result.ptr == end;
  };
  return parse(field[1], number) && parse(field[4], level);
}

// Append `s` as the body of a C++ string literal, escaping what would change
// the bytes if it were not.
void appendEscaped(std::string &out, std::string_view s) {
  for (char const c : s) {
    switch (c) {
    case '\\':
      out += "\\\\";
      break;
    case '"':
      out += "\\\"";
      break;
    case '\n':
      out += "\\n";
      break;
    case '\r':
      out += "\\r";
      break;
    case '\t':
      out += "\\t";
      break;
    default:
      out.push_back(c);
      break;
    }
  }
}

void appendEntry(std::string &out, Entry const &entry) {
  out += "    {FbcMessageKind::";
  out += entry.warning ? "Warning" : "Error";
  out += ", ";
  out += std::to_string(entry.number);
  out += ", \"";
  appendEscaped(out, entry.name);
  out += "\", \"";
  appendEscaped(out, entry.text);
  out += "\", ";
  out += std::to_string(entry.level);
  out += "},\n";
}

} // namespace

std::vector<Entry> parseCatalog(std::string_view tsv) {
  std::vector<Entry> out;
  std::size_t pos = 0;
  while (pos <= tsv.size()) {
    std::size_t const end = tsv.find('\n', pos);
    std::string_view line =
        tsv.substr(pos, end == std::string_view::npos ? std::string_view::npos
                                                      : end - pos);
    if (!line.empty() && line.back() == '\r') {
      line.remove_suffix(1);
    }
    if (!line.empty() && line.front() != '#') {
      std::string_view kind;
      std::string_view name;
      std::string_view text;
      int number = 0;
      int level = 0;
      if (splitRow(line, kind, number, name, text, level)) {
        Entry entry;
        entry.warning = kind == "W";
        entry.number = number;
        entry.name.assign(name);
        entry.text.assign(text);
        entry.level = level;
        out.push_back(std::move(entry));
      }
    }
    if (end == std::string_view::npos) {
      break;
    }
    pos = end + 1;
  }
  return out;
}

std::string emitCatalogInclude(std::vector<Entry> const &entries) {
  std::string out;
  out +=
      "// Generated by tools/gen_fbc_catalog.cpp from tools/fbc_catalog.tsv.\n";
  out += "// fbc 1.10.2 (8e1023e3). Do not edit by hand; regenerate with\n";
  out += "// `cmake --build <build> --target fbc-catalog`.\n";
  out += "static constexpr FbcCatalogEntry kFbcErrors[] = {\n";
  int errors = 0;
  for (Entry const &entry : entries) {
    if (!entry.warning) {
      appendEntry(out, entry);
      ++errors;
    }
  }
  out += "};\n";
  out += "static constexpr FbcCatalogEntry kFbcWarnings[] = {\n";
  int warnings = 0;
  for (Entry const &entry : entries) {
    if (entry.warning) {
      appendEntry(out, entry);
      ++warnings;
    }
  }
  out += "};\n";
  out +=
      "static constexpr int kFbcErrorCount = " + std::to_string(errors) + ";\n";
  out += "static constexpr int kFbcWarningCount = " + std::to_string(warnings) +
         ";\n";
  return out;
}

} // namespace fbc_catalog
